from .index import index
from .home import home
from .login_user import login_user
from .logout_user import logout_user
from .product import product
from .product import update_product
from .product import update_product_auto
from .submit_barcode import submit_barcode
from .submit_barcode import submit_barcode_auto
from .warehouse import warehouse
from .serial import serial
from .reportserial import ReportSerial
