# Generated by Django 4.2.20 on 2025-04-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_comment='The name of the product', max_length=100, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, db_comment='The unique code of the product', max_length=100, null=True, verbose_name='code')),
                ('amount', models.PositiveBigIntegerField(blank=True, db_comment='The quantity or amount of the product', null=True, verbose_name='amount')),
                ('description', models.PositiveBigIntegerField(blank=True, db_comment='Description of the product', null=True, verbose_name='description')),
                ('dateProduct', models.DateTimeField(blank=True, db_comment='The date of production or arrival of the product', null=True)),
                ('exporter', models.CharField(blank=True, db_comment='Name of the exporter of the product', max_length=100, null=True, verbose_name='exporter')),
                ('remittanceArrived', models.PositiveBigIntegerField(blank=True, db_comment='Indicates whether the remittance or payment has arrived', null=True, verbose_name='remittance_arrived')),
                ('typeID', models.CharField(blank=True, choices=[('1000', 'حواله مستقیم'), ('101', 'حواله فروش'), ('102', 'حواله برگشت خرید'), ('1', 'رسید خرید'), ('0', 'رسید مستقیم'), ('2', 'رسید برگشت فروش'), ('103', 'حواله انتقال بین انبار'), ('3', 'رسید انتقال بین انبار')], max_length=20, null=True, verbose_name='typeID')),
                ('allow', models.BooleanField(blank=True, db_comment='True is allow and False is not allow', default=False, null=True, verbose_name='allow')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time when the record was created', null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='The date and time when the record was last updated', null=True, verbose_name='updated_at')),
                ('is_deleted', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'db_table_comment': 'Table containing product information',
            },
        ),
        migrations.CreateModel(
            name='ProductWH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_comment='The name of the product', max_length=100, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, db_comment='The unique code of the product', max_length=100, null=True, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time when the record was created', null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='The date and time when the record was last updated', null=True, verbose_name='updated_at')),
                ('is_deleted', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'ProductWH',
                'verbose_name_plural': 'ProductsWH',
                'db_table': 'productWH',
                'db_table_comment': 'Table containing product information',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfProd', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the order was placed', verbose_name='date_of_prod')),
                ('CodeProd', models.CharField(blank=True, db_comment='The unique code of the product', max_length=100, null=True, verbose_name='code_prod')),
                ('NameProd', models.CharField(blank=True, db_comment='The product associated with this order', max_length=100, null=True, verbose_name='name_prod')),
                ('difference', models.IntegerField(blank=True, db_comment='The unique code of the product', null=True, verbose_name='difference')),
                ('countOfNumber', models.CharField(blank=True, choices=[('1', 'شمارش اول'), ('2', 'شمارش دوم'), ('3', 'شمارش سوم')], max_length=10, null=True, verbose_name='countOfNumber')),
                ('user_issuer', models.CharField(blank=True, db_comment='The product associated with this order', max_length=100, null=True, verbose_name='user_issuer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the order was placed', verbose_name='serial_created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='The date and time when the record was last updated', verbose_name='serial_updated')),
                ('is_deleted', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Serials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialProduct', models.CharField(blank=True, db_comment='The serial of the product', max_length=100, null=True, verbose_name='serial_product')),
                ('user_issuer', models.CharField(blank=True, db_comment='The product associated with this order', max_length=10, null=True, verbose_name='user_issuer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the order was placed', verbose_name='serial_created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='The date and time when the record was last updated', verbose_name='serial_updated')),
                ('is_deleted', models.BooleanField(default=0)),
                ('productID', models.ForeignKey(blank=True, db_comment='The product associated with this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='app.product', verbose_name='product_id')),
            ],
        ),
    ]
